#![allow(unexpected_cfgs)]
#![allow(clippy::too_many_arguments)] // Generated by TxLINE's official IDL.

use anchor_lang::prelude::*;
use anchor_spl::{
    associated_token::AssociatedToken,
    token::{self, Mint, MintTo, Token, TokenAccount, Transfer},
};

declare_program!(txoracle);
declare_id!("BgJSdxW7zKzg5r5sctQoxEbc73pEeiaFGj3ebqvR8gnd");

const PLAY_DECIMALS: u8 = 6;
const DEMO_PLAY_AMOUNT: u64 = 1_000 * 10_u64.pow(PLAY_DECIMALS as u32);

#[program]
pub mod vericup {
    use super::*;

    pub fn initialize_protocol(ctx: Context<InitializeProtocol>) -> Result<()> {
        let config = &mut ctx.accounts.config;
        config.authority = ctx.accounts.authority.key();
        config.play_mint = ctx.accounts.play_mint.key();
        config.bump = ctx.bumps.config;
        Ok(())
    }

    pub fn claim_demo_tokens(ctx: Context<ClaimDemoTokens>) -> Result<()> {
        let signer_seeds: &[&[u8]] = &[b"config", &[ctx.accounts.config.bump]];
        token::mint_to(
            CpiContext::new_with_signer(
                ctx.accounts.token_program.to_account_info(),
                MintTo {
                    mint: ctx.accounts.play_mint.to_account_info(),
                    to: ctx.accounts.user_play.to_account_info(),
                    authority: ctx.accounts.config.to_account_info(),
                },
                &[signer_seeds],
            ),
            DEMO_PLAY_AMOUNT,
        )?;

        let receipt = &mut ctx.accounts.faucet_receipt;
        receipt.user = ctx.accounts.user.key();
        receipt.bump = ctx.bumps.faucet_receipt;
        Ok(())
    }

    pub fn create_market(ctx: Context<CreateMarket>, fixture_id: u64, kickoff: i64) -> Result<()> {
        require!(
            kickoff > Clock::get()?.unix_timestamp,
            VeriCupError::InvalidKickoff
        );

        let market = &mut ctx.accounts.market;
        market.fixture_id = fixture_id;
        market.kickoff = kickoff;
        market.play_mint = ctx.accounts.play_mint.key();
        market.vault = ctx.accounts.vault.key();
        market.state = MarketState::Open;
        market.pools = [0; 3];
        market.resolved_outcome = None;
        market.proof_hash = [0; 32];
        market.resolution_slot = 0;
        market.claimed_winning_stake = 0;
        market.claimed_payout = 0;
        market.bump = ctx.bumps.market;
        Ok(())
    }

    pub fn take_position(ctx: Context<TakePosition>, outcome: Outcome, amount: u64) -> Result<()> {
        require!(amount > 0, VeriCupError::InvalidAmount);
        require!(
            ctx.accounts.market.state == MarketState::Open,
            VeriCupError::MarketClosed
        );
        require!(
            Clock::get()?.unix_timestamp < ctx.accounts.market.kickoff,
            VeriCupError::MarketClosed
        );

        let outcome_index = outcome.index();
        let position = &mut ctx.accounts.position;
        if position.amount == 0 {
            position.owner = ctx.accounts.user.key();
            position.market = ctx.accounts.market.key();
            position.outcome = outcome;
            position.bump = ctx.bumps.position;
        }
        position.amount = position
            .amount
            .checked_add(amount)
            .ok_or(VeriCupError::ArithmeticOverflow)?;

        let market = &mut ctx.accounts.market;
        market.pools[outcome_index] = market.pools[outcome_index]
            .checked_add(amount)
            .ok_or(VeriCupError::ArithmeticOverflow)?;

        token::transfer(
            CpiContext::new(
                ctx.accounts.token_program.to_account_info(),
                Transfer {
                    from: ctx.accounts.user_play.to_account_info(),
                    to: ctx.accounts.vault.to_account_info(),
                    authority: ctx.accounts.user.to_account_info(),
                },
            ),
            amount,
        )
    }

    pub fn lock_market(ctx: Context<LockMarket>) -> Result<()> {
        require!(
            ctx.accounts.market.state == MarketState::Open,
            VeriCupError::MarketClosed
        );
        require!(
            Clock::get()?.unix_timestamp >= ctx.accounts.market.kickoff,
            VeriCupError::MarketStillOpen
        );
        ctx.accounts.market.state = MarketState::Locked;
        Ok(())
    }

    pub fn resolve_with_txline(
        ctx: Context<ResolveWithTxline>,
        payload: txoracle::types::StatValidationInput,
    ) -> Result<()> {
        use txoracle::types::{Comparison, NDimensionalStrategy, StatPredicate, TraderPredicate};

        require!(
            ctx.accounts.market.state == MarketState::Locked,
            VeriCupError::MarketNotLocked
        );
        require!(
            payload.fixture_summary.fixture_id >= 0
                && payload.fixture_summary.fixture_id as u64 == ctx.accounts.market.fixture_id,
            VeriCupError::FixtureMismatch
        );
        require!(payload.stats.len() == 2, VeriCupError::InvalidScoreProof);

        let home = &payload.stats[0].stat;
        let away = &payload.stats[1].stat;
        require!(
            home.key == 1 && away.key == 2,
            VeriCupError::InvalidScoreProof
        );
        require!(
            home.period == 100 && away.period == 100,
            VeriCupError::ScoreNotFinal
        );
        require!(
            home.value >= 0 && away.value >= 0,
            VeriCupError::InvalidScoreProof
        );

        let strategy = NDimensionalStrategy {
            geometric_targets: vec![],
            distance_predicate: None,
            discrete_predicates: vec![
                StatPredicate::Single {
                    index: 0,
                    predicate: TraderPredicate {
                        threshold: home.value,
                        comparison: Comparison::EqualTo,
                    },
                },
                StatPredicate::Single {
                    index: 1,
                    predicate: TraderPredicate {
                        threshold: away.value,
                        comparison: Comparison::EqualTo,
                    },
                },
            ],
        };
        let proof_hash = solana_keccak_hasher::hash(&payload.try_to_vec()?).to_bytes();
        let home_score = home.value;
        let away_score = away.value;

        txoracle::cpi::validate_stat_v2(
            CpiContext::new(
                ctx.accounts.txoracle_program.to_account_info(),
                txoracle::cpi::accounts::ValidateStatV2 {
                    daily_scores_merkle_roots: ctx
                        .accounts
                        .daily_scores_merkle_roots
                        .to_account_info(),
                },
            ),
            payload,
            strategy,
        )?;

        let (returning_program, return_data) =
            anchor_lang::solana_program::program::get_return_data()
                .ok_or(VeriCupError::MissingOracleReturn)?;
        require_keys_eq!(
            returning_program,
            txoracle::ID,
            VeriCupError::InvalidOracleReturn
        );
        let verified = bool::try_from_slice(&return_data)
            .map_err(|_| error!(VeriCupError::InvalidOracleReturn))?;
        require!(verified, VeriCupError::ProofRejected);

        let market = &mut ctx.accounts.market;
        market.resolved_outcome = Some(if home_score > away_score {
            Outcome::Home
        } else if home_score < away_score {
            Outcome::Away
        } else {
            Outcome::Draw
        });
        market.proof_hash = proof_hash;
        market.resolution_slot = Clock::get()?.slot;
        market.state = MarketState::Resolved;
        Ok(())
    }

    pub fn claim_payout(ctx: Context<SettlePosition>, _outcome: Outcome) -> Result<()> {
        let market = &mut ctx.accounts.market;
        require!(
            market.state == MarketState::Resolved,
            VeriCupError::MarketNotResolved
        );
        require!(!ctx.accounts.position.claimed, VeriCupError::AlreadyClaimed);

        let winner = market
            .resolved_outcome
            .ok_or(VeriCupError::MarketNotResolved)?;
        require!(
            ctx.accounts.position.outcome == winner,
            VeriCupError::WrongOutcome
        );

        let total_pool = market
            .pools
            .iter()
            .try_fold(0_u64, |sum, value| sum.checked_add(*value))
            .ok_or(VeriCupError::ArithmeticOverflow)?;
        let winner_pool = market.pools[winner.index()];
        require!(winner_pool > 0, VeriCupError::NoWinningPool);

        let claimed_winning_stake = market
            .claimed_winning_stake
            .checked_add(ctx.accounts.position.amount)
            .ok_or(VeriCupError::ArithmeticOverflow)?;
        require!(
            claimed_winning_stake <= winner_pool,
            VeriCupError::ArithmeticOverflow
        );
        let payout = if claimed_winning_stake == winner_pool {
            total_pool
                .checked_sub(market.claimed_payout)
                .ok_or(VeriCupError::ArithmeticOverflow)?
        } else {
            u64::try_from(
                (u128::from(ctx.accounts.position.amount) * u128::from(total_pool))
                    / u128::from(winner_pool),
            )
            .map_err(|_| error!(VeriCupError::ArithmeticOverflow))?
        };

        ctx.accounts.position.claimed = true;
        market.claimed_winning_stake = claimed_winning_stake;
        market.claimed_payout = market
            .claimed_payout
            .checked_add(payout)
            .ok_or(VeriCupError::ArithmeticOverflow)?;

        transfer_market_tokens(&ctx, payout)
    }

    pub fn refund_position(ctx: Context<SettlePosition>, _outcome: Outcome) -> Result<()> {
        let market = &ctx.accounts.market;
        require!(
            market.state == MarketState::Resolved,
            VeriCupError::MarketNotResolved
        );
        require!(!ctx.accounts.position.claimed, VeriCupError::AlreadyClaimed);
        let winner = market
            .resolved_outcome
            .ok_or(VeriCupError::MarketNotResolved)?;
        require!(
            market.pools[winner.index()] == 0,
            VeriCupError::WinningPoolExists
        );

        let refund = ctx.accounts.position.amount;
        ctx.accounts.position.claimed = true;
        transfer_market_tokens(&ctx, refund)
    }
}

fn transfer_market_tokens(ctx: &Context<SettlePosition>, amount: u64) -> Result<()> {
    let fixture_bytes = ctx.accounts.market.fixture_id.to_le_bytes();
    let bump = [ctx.accounts.market.bump];
    let signer_seeds: &[&[u8]] = &[b"market", fixture_bytes.as_ref(), bump.as_ref()];
    token::transfer(
        CpiContext::new_with_signer(
            ctx.accounts.token_program.to_account_info(),
            Transfer {
                from: ctx.accounts.vault.to_account_info(),
                to: ctx.accounts.user_play.to_account_info(),
                authority: ctx.accounts.market.to_account_info(),
            },
            &[signer_seeds],
        ),
        amount,
    )
}

#[derive(Accounts)]
pub struct InitializeProtocol<'info> {
    #[account(mut)]
    pub authority: Signer<'info>,
    #[account(
        init,
        payer = authority,
        space = 8 + ProtocolConfig::INIT_SPACE,
        seeds = [b"config"],
        bump
    )]
    pub config: Account<'info, ProtocolConfig>,
    #[account(
        mut,
        constraint = play_mint.decimals == PLAY_DECIMALS @ VeriCupError::InvalidPlayMint,
        constraint = play_mint.mint_authority == anchor_lang::solana_program::program_option::COption::Some(config.key()) @ VeriCupError::InvalidPlayMint
    )]
    pub play_mint: Account<'info, Mint>,
    pub system_program: Program<'info, System>,
}

#[derive(Accounts)]
pub struct ClaimDemoTokens<'info> {
    #[account(mut)]
    pub user: Signer<'info>,
    #[account(seeds = [b"config"], bump = config.bump)]
    pub config: Account<'info, ProtocolConfig>,
    #[account(mut, address = config.play_mint)]
    pub play_mint: Account<'info, Mint>,
    #[account(
        mut,
        token::mint = play_mint,
        token::authority = user
    )]
    pub user_play: Account<'info, TokenAccount>,
    #[account(
        init,
        payer = user,
        space = 8 + FaucetReceipt::INIT_SPACE,
        seeds = [b"faucet", config.key().as_ref(), user.key().as_ref()],
        bump
    )]
    pub faucet_receipt: Account<'info, FaucetReceipt>,
    pub token_program: Program<'info, Token>,
    pub system_program: Program<'info, System>,
}

#[derive(Accounts)]
#[instruction(fixture_id: u64)]
pub struct CreateMarket<'info> {
    #[account(mut)]
    pub authority: Signer<'info>,
    #[account(
        seeds = [b"config"],
        bump = config.bump,
        has_one = authority,
        has_one = play_mint
    )]
    pub config: Account<'info, ProtocolConfig>,
    pub play_mint: Account<'info, Mint>,
    #[account(
        init,
        payer = authority,
        space = 8 + Market::INIT_SPACE,
        seeds = [b"market".as_ref(), fixture_id.to_le_bytes().as_ref()],
        bump
    )]
    pub market: Account<'info, Market>,
    #[account(
        init,
        payer = authority,
        associated_token::mint = play_mint,
        associated_token::authority = market
    )]
    pub vault: Account<'info, TokenAccount>,
    pub token_program: Program<'info, Token>,
    pub associated_token_program: Program<'info, AssociatedToken>,
    pub system_program: Program<'info, System>,
}

#[derive(Accounts)]
#[instruction(outcome: Outcome)]
pub struct TakePosition<'info> {
    #[account(mut)]
    pub user: Signer<'info>,
    #[account(
        mut,
        seeds = [b"market".as_ref(), market.fixture_id.to_le_bytes().as_ref()],
        bump = market.bump
    )]
    pub market: Account<'info, Market>,
    #[account(
        init_if_needed,
        payer = user,
        space = 8 + Position::INIT_SPACE,
        seeds = [b"position".as_ref(), market.key().as_ref(), user.key().as_ref(), &[outcome.index() as u8]],
        bump
    )]
    pub position: Account<'info, Position>,
    #[account(
        mut,
        token::mint = market.play_mint,
        token::authority = user
    )]
    pub user_play: Account<'info, TokenAccount>,
    #[account(mut, address = market.vault)]
    pub vault: Account<'info, TokenAccount>,
    pub token_program: Program<'info, Token>,
    pub system_program: Program<'info, System>,
}

#[derive(Accounts)]
pub struct LockMarket<'info> {
    #[account(
        mut,
        seeds = [b"market".as_ref(), market.fixture_id.to_le_bytes().as_ref()],
        bump = market.bump
    )]
    pub market: Account<'info, Market>,
}

#[derive(Accounts)]
pub struct ResolveWithTxline<'info> {
    #[account(
        mut,
        seeds = [b"market".as_ref(), market.fixture_id.to_le_bytes().as_ref()],
        bump = market.bump
    )]
    pub market: Account<'info, Market>,
    /// CHECK: TxLINE validates this account during the CPI.
    pub daily_scores_merkle_roots: UncheckedAccount<'info>,
    pub txoracle_program: Program<'info, txoracle::program::Txoracle>,
}

#[derive(Accounts)]
#[instruction(outcome: Outcome)]
pub struct SettlePosition<'info> {
    #[account(mut)]
    pub user: Signer<'info>,
    #[account(
        mut,
        seeds = [b"market".as_ref(), market.fixture_id.to_le_bytes().as_ref()],
        bump = market.bump
    )]
    pub market: Account<'info, Market>,
    #[account(
        mut,
        seeds = [b"position".as_ref(), market.key().as_ref(), user.key().as_ref(), &[outcome.index() as u8]],
        bump = position.bump,
        has_one = market,
        constraint = position.owner == user.key() @ VeriCupError::WrongOwner,
        constraint = position.outcome == outcome @ VeriCupError::WrongOutcome
    )]
    pub position: Account<'info, Position>,
    #[account(
        mut,
        address = market.vault,
        token::mint = market.play_mint,
        token::authority = market
    )]
    pub vault: Account<'info, TokenAccount>,
    #[account(
        mut,
        token::mint = market.play_mint,
        token::authority = user
    )]
    pub user_play: Account<'info, TokenAccount>,
    pub token_program: Program<'info, Token>,
}

#[account]
#[derive(InitSpace)]
pub struct ProtocolConfig {
    pub authority: Pubkey,
    pub play_mint: Pubkey,
    pub bump: u8,
}

#[account]
#[derive(InitSpace)]
pub struct FaucetReceipt {
    pub user: Pubkey,
    pub bump: u8,
}

#[account]
#[derive(InitSpace)]
pub struct Market {
    pub fixture_id: u64,
    pub kickoff: i64,
    pub play_mint: Pubkey,
    pub vault: Pubkey,
    pub state: MarketState,
    pub pools: [u64; 3],
    pub resolved_outcome: Option<Outcome>,
    pub proof_hash: [u8; 32],
    pub resolution_slot: u64,
    pub claimed_winning_stake: u64,
    pub claimed_payout: u64,
    pub bump: u8,
}

#[account]
#[derive(InitSpace)]
pub struct Position {
    pub owner: Pubkey,
    pub market: Pubkey,
    pub outcome: Outcome,
    pub amount: u64,
    pub claimed: bool,
    pub bump: u8,
}

#[derive(AnchorSerialize, AnchorDeserialize, Clone, Copy, PartialEq, Eq, InitSpace)]
pub enum MarketState {
    Open,
    Locked,
    Resolved,
}

#[derive(AnchorSerialize, AnchorDeserialize, Clone, Copy, PartialEq, Eq, InitSpace)]
pub enum Outcome {
    Home,
    Draw,
    Away,
}

impl Outcome {
    fn index(self) -> usize {
        match self {
            Self::Home => 0,
            Self::Draw => 1,
            Self::Away => 2,
        }
    }
}

#[error_code]
pub enum VeriCupError {
    #[msg("The PLAY mint is not configured for this protocol")]
    InvalidPlayMint,
    #[msg("Kickoff must be in the future")]
    InvalidKickoff,
    #[msg("Position amount must be greater than zero")]
    InvalidAmount,
    #[msg("Market is not accepting positions")]
    MarketClosed,
    #[msg("Market cannot be locked before kickoff")]
    MarketStillOpen,
    #[msg("Market must be locked before resolution")]
    MarketNotLocked,
    #[msg("TxLINE proof fixture does not match the market")]
    FixtureMismatch,
    #[msg("TxLINE proof must contain the final home and away score leaves")]
    InvalidScoreProof,
    #[msg("TxLINE score leaves are not final")]
    ScoreNotFinal,
    #[msg("TxLINE did not return a validation result")]
    MissingOracleReturn,
    #[msg("TxLINE returned malformed validation data")]
    InvalidOracleReturn,
    #[msg("TxLINE rejected the submitted Merkle proof")]
    ProofRejected,
    #[msg("Market has not been resolved")]
    MarketNotResolved,
    #[msg("Only winning positions can claim a payout")]
    WrongOutcome,
    #[msg("Position does not belong to this wallet")]
    WrongOwner,
    #[msg("This position was already settled")]
    AlreadyClaimed,
    #[msg("The resolved outcome has no winning pool")]
    NoWinningPool,
    #[msg("Refunds are unavailable because the resolved outcome has winners")]
    WinningPoolExists,
    #[msg("Arithmetic overflow")]
    ArithmeticOverflow,
}
